//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgebraApp1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSignUp
    {
        public int IdCourseSignUp { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int IdCourse { get; set; }
        public bool Status { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
